# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='username',
            name='user_name',
        ),
        migrations.AddField(
            model_name='username',
            name='username',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
