# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171010_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='catagory',
            new_name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='food_type',
            field=models.CharField(choices=[('bf', 'Breakfast'), ('lun', 'Lunch'), ('din', 'Dinner')], default='bf', max_length=3),
        ),
    ]
