# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171010_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='code',
            field=models.CharField(default='np', max_length=1000),
        ),
    ]
