# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='vendor_image',
            field=models.FileField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
