# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171010_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('foodname', models.CharField(max_length=1000)),
                ('prepared', models.IntegerField(default='0')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vendor')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('VEG', 'Vegetarian'), ('NON', 'Non-Vegetarian'), ('SOF', 'Soft-Drinks'), ('BEV', 'Beverages')], default='VEG', max_length=3, verbose_name='Category'),
        ),
    ]
